version: "3"
services:
  
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
  
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes: 
      - /app/node_modules
      - ./backend:/app
    ports: 
      - "5000:5000"
    environment: 
      DB_HOST: `echo $DB_HOST`
      DB_USER: `echo $DB_USER`
      DB_PASSWORD: `echo $DB_PASSWORD`
      DB_DEFAULT_DB: `echo $DB_DEFAULT_DB`
      NODE_ENV: `echo $NODE_ENV`
      MYSQL_PORT: `echo $MYSQL_PORT`
    
  
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
    


