version: "3"
services:
  
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
  
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes: 
      - /app/node_modules
      - ./backend:/app
    ports: 
      - "5000:5000"
    environment: 
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DEFAULT_DB: $DB_DEFAULT_DB
      NODE_ENV: $NODE_ENV
      MYSQL_PORT: $MYSQL_PORT
    
  
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes: 
      - /etc/letsencrypt/live/blog.whmydeal.xyz:/etc/letsencrypt/live/blog.whmydeal.xyz
    ports: 
      - "3000:80"
    


